-------------------------------------------------------------------------------
--  Author: siriusjs
--  Date: 4/8/12
--  Description: This files contains conversion tables needed for the addon 
--      TabardAlert.
-------------------------------------------------------------------------------

-- This table was generated by hand from the information on www.wowhead.com.
-- It is used to convert a tabard id to a faction id.
TabardAlert_TabardToFaction = {
    ----------------------
    -- Alliance Classic --
    ----------------------
    -- Stormwind
    ["45574"] = 72,
    -- IronForge
    ["45577"] = 47,
    -- Gnomeregan
    ["45578"] = 54,
    -- Darnassus
    ["45579"] = 69,
    -- Exodar
    ["45580"] = 930,
    -- Gilneas
    ["64882"] = 1134,
    
    -------------------
    -- Horde Classic --
    -------------------
    -- Orgrimmar 
    ["45581"] = 76,
    -- Darkspear 
    ["45582"] = 530,
    -- Thunderbluff
    ["45584"] = 81,
    -- Undercity
    ["45583"] = 68,
    -- Silvermoon
    ["45585"] = 911,    
    -- Bilgewater Cartel
    ["64884"] = 1133,
   
    ---------------------
    -- Burning Crusade --
    --------------------- 
    -- None 
    
    ----------------------------
    -- Wrath of the Lich King --
    ----------------------------
    -- Argent Crusade
    ["43154"] = 1106,
    -- Ebon Blade
    ["43155"] = 1098,
    -- Kirin Tor
    ["43157"] = 1090,
    -- Wyrmrest Accord
    ["43156"] = 1091,
    
    ---------------
    -- Cataclysm --
    ---------------
    -- Guardians of Hyjal
    ["65906"] = 1158,
    -- Earthen Ring
    ["65905"] = 1135,
    -- Therazane
    ["65907"] = 1171,
    -- Ramkahen
    ["65904"] = 1173,
    -- WildHammer Clan
    ["65908"] = 1174,
    -- Dragonmaw Clan
    ["65909"] = 1172,
    
    -----------------------
    -- Mists of Pandaria --
    -----------------------
    -- Soon...
}
